services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "StrongPass123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - fullstack-network
    restart: unless-stopped

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mssql://sa:StrongPass123!@db:1433/formsdb?driver=ODBC+Driver+17+for+SQL+Server&TrustServerCertificate=yes
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
      - DJANGO_SETTINGS_MODULE=backend.settings_sqlserver
      - DB_HOST=db
      - DB_PORT=1433
      - DB_NAME=formsdb
      - DB_USER=sa
      - DB_PASSWORD=StrongPass123!
    volumes:
      - ./backend:/app
    networks:
      - fullstack-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - fullstack-network

volumes:
  sqlserver_data:

networks:
  fullstack-network:
    driver: bridge
