# Generated by Django 5.2.4 on 2025-07-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_citizenfeedback_related_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenfeedback',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='العمر'),
        ),
        migrations.AddField(
            model_name='citizenfeedback',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='citizenfeedback',
            name='consent_contact',
            field=models.BooleanField(default=False, verbose_name='موافقة التواصل'),
        ),
        migrations.AddField(
            model_name='citizenfeedback',
            name='consent_data_processing',
            field=models.BooleanField(default=False, verbose_name='موافقة معالجة البيانات'),
        ),
        migrations.AddField(
            model_name='citizenfeedback',
            name='education_level',
            field=models.CharField(blank=True, choices=[('primary', 'ابتدائي'), ('intermediate', 'متوسط'), ('secondary', 'ثانوي'), ('diploma', 'دبلوم'), ('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('phd', 'دكتوراه')], max_length=20, null=True, verbose_name='المستوى التعليمي'),
        ),
        migrations.AddField(
            model_name='citizenfeedback',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, null=True, verbose_name='الجنس'),
        ),
        migrations.AddField(
            model_name='citizenfeedback',
            name='governorate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='citizenfeedback',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المهنة'),
        ),
        migrations.AddField(
            model_name='citizenfeedback',
            name='preferred_contact_method',
            field=models.CharField(blank=True, choices=[('email', 'البريد الإلكتروني'), ('phone', 'الهاتف'), ('sms', 'الرسائل النصية'), ('mail', 'البريد العادي')], max_length=20, null=True, verbose_name='طريقة التواصل المفضلة'),
        ),
        migrations.AddField(
            model_name='citizenfeedback',
            name='previous_attempts',
            field=models.BooleanField(default=False, verbose_name='محاولات سابقة'),
        ),
        migrations.AddField(
            model_name='citizenfeedback',
            name='previous_attempts_description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف المحاولات السابقة'),
        ),
    ]
