# Generated by Django 5.2.4 on 2025-07-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_add_citizenfeedback_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenfeedback',
            name='citizen_address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='citizenfeedback',
            name='citizen_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='citizenfeedback',
            name='citizen_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='citizenfeedback',
            name='citizen_phone',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='رقم الهاتف'),
        ),
    ]
