# Generated by Django 4.2.7 on 2025-07-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_make_citizen_fields_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenfeedback',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الإدارة'),
        ),
        migrations.AlterField(
            model_name='citizenfeedback',
            name='citizen_address',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='citizenfeedback',
            name='citizen_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='citizenfeedback',
            name='citizen_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='citizenfeedback',
            name='citizen_phone',
            field=models.CharField(blank=True, max_length=17, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='citizenfeedback',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='citizenfeedback',
            name='education_level',
            field=models.CharField(blank=True, choices=[('primary', 'ابتدائي'), ('intermediate', 'متوسط'), ('secondary', 'ثانوي'), ('diploma', 'دبلوم'), ('bachelor', 'بكالوريوس'), ('master', 'ماجستير'), ('phd', 'دكتوراه')], max_length=20, verbose_name='المستوى التعليمي'),
        ),
        migrations.AlterField(
            model_name='citizenfeedback',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='citizenfeedback',
            name='governorate',
            field=models.CharField(blank=True, max_length=50, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='citizenfeedback',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='المهنة'),
        ),
        migrations.AlterField(
            model_name='citizenfeedback',
            name='preferred_contact_method',
            field=models.CharField(blank=True, choices=[('email', 'البريد الإلكتروني'), ('phone', 'الهاتف'), ('sms', 'الرسائل النصية'), ('mail', 'البريد العادي')], max_length=20, verbose_name='طريقة التواصل المفضلة'),
        ),
        migrations.AlterField(
            model_name='citizenfeedback',
            name='previous_attempts_description',
            field=models.TextField(blank=True, verbose_name='وصف المحاولات السابقة'),
        ),
        migrations.AlterField(
            model_name='citizenfeedback',
            name='resolution',
            field=models.TextField(blank=True, verbose_name='الحل المتخذ'),
        ),
        migrations.AlterField(
            model_name='governmententity',
            name='additional_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات إضافية'),
        ),
        migrations.AlterField(
            model_name='governmententity',
            name='international_cooperation',
            field=models.TextField(blank=True, verbose_name='التعاون الدولي'),
        ),
        migrations.AlterField(
            model_name='governmententity',
            name='partnerships',
            field=models.TextField(blank=True, verbose_name='الشراكات مع جهات أخرى'),
        ),
        migrations.AlterField(
            model_name='governmententity',
            name='quality_certificate_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='نوع شهادة الجودة'),
        ),
        migrations.AlterField(
            model_name='governmententity',
            name='system_description',
            field=models.TextField(blank=True, verbose_name='وصف النظام الإلكتروني'),
        ),
    ]
