# Generated by Django 5.2.4 on 2025-07-26 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الاستمارة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الاستمارة')),
                ('category', models.CharField(choices=[('general', 'عام'), ('feedback', 'ملاحظات واقتراحات'), ('complaints', 'شكاوى'), ('services', 'طلب خدمات'), ('employment', 'توظيف'), ('surveys', 'استطلاعات رأي')], default='general', max_length=50, verbose_name='فئة الاستمارة')),
                ('fields', models.JSONField(verbose_name='حقول الاستمارة')),
                ('is_public', models.BooleanField(default=True, verbose_name='استمارة عامة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='منشئ الاستمارة')),
            ],
            options={
                'verbose_name': 'استمارة مخصصة',
                'verbose_name_plural': 'استمارات مخصصة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.JSONField(verbose_name='بيانات الرد')),
                ('submitter_name', models.CharField(max_length=255, verbose_name='اسم المرسل')),
                ('submitter_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='بريد المرسل')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='custom_forms.customform', verbose_name='الاستمارة')),
            ],
            options={
                'verbose_name': 'رد استمارة',
                'verbose_name_plural': 'ردود الاستمارات',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
